### ISSUE TITLE
Documentation for keybinding issue

### ISSUE THREAD

**Issue by hoop33** [imsnif/monocle#1]
Fairly new to zellij and new to plugins. This looks pretty cool. The documentation for setting up the keybinding seems amiss -- `file:strider` seems to point to the strider plugin. I set up it like this:

```
bind "F1" {
    LaunchOrFocusPlugin "file:~/zellij-plugins/monocle" {
        floating true
    }
}
```

I can open a PR if you'd like.

**Comment by imsnif** [comment]
Oh my goodness! That's what I get for copy/pasting. I'd love a PR.
