### ISSUE TITLE
monocle extremelly slow causes zellij to eat CPU and hang

### ISSUE THREAD

**Issue by salva-ferrer** [imsnif/monocle#15]
Hi, I just clicked the monocle keybindings and realized its behavior was not as usual: The floating pane was stuck on the loading messages, without moving to the find: prompt. After some time, a zellij process was eating CPU to the extent of a slowdown of the system being noticeable. Given enough time, the find: prompt appears, but zellij doesn't respond to any key presses in the search panel.

I tried in several dirs making sure there were no device nor special files on the dirs.

I'm using zellij 0.39.2 in alacritty 0.13.1 but downloaded the latest monocle available, 0.39.0. 

I know for sure the monocle worked ok with zellij 0.39.0 so it may be just some incompatibility with the newer version.

This is not critical to me, let me know if I can be of any help to diagnose this behavior.

regards

**Comment by imsnif** [comment]
Thanks for the report! I'm pretty sure this has to do with the filesystem watch interface which is... not great, to say the least. Locally for me I compiled a version without it, I plan to remove it in the next version as I think long-lasting monocle sessions are not really what this plugin is used for after all (at least by me).

**Comment by imsnif** [comment]
This should be fixed in v0.100.0
