### ISSUE TITLE
Doesn't start then breaks Zellij

### ISSUE THREAD

**Issue by ghost** [imsnif/monocle#3]
I get this when I first start the plugin:

![image](https://github.com/imsnif/monocle/assets/60433637/795d74c2-fdb9-4145-82e9-23183fe2682e)

Then nothing happens. If I try to relaunch the plugin it doesn't output anything and zellij goes completely unresponsive including the cli so I have to kill the processes.

I am on Linux and zellij v0.37.2. If you could point me to logs I can provide more information.

**Comment by imsnif** [comment]
I've seen this too - I think this happens because Zellij was opened in a folder with lots of files, then monocle tried to place everything in memory and finally dies. I want to add a limit of some sort and indicate this to the user (also I want to make it open to the CWD of the focused pane to avoid this 99% of the time, but that's another issue)

**Comment by ghost** [comment]
Actually, it doesn't work anywhere for me. Although I just tried to use strider and a similar thing happened so maybe it's a zellij issue and not plugin specific?

**Comment by imsnif** [comment]
Could be... do you get a stacktrace or some other error?

**Comment by ghost** [comment]
No other errors or outputs, just freezes

**Comment by imsnif** [comment]
So other panes still work? How did you load it?

**Comment by hunger** [comment]
Please make it open on the CWD of the current pane. That would make the entire thing so much more useful!

**Comment by imsnif** [comment]
> Please make it open on the CWD of the current pane. That would make the entire thing so much more useful!

That's the plan!

**Comment by abneb** [comment]
I'm facing the same behavior. In my case took around 10 seconds then it good to go. Only if I spawn a new terminal and zellij again it has to repeat the process.

**Comment by dmgolembiowski** [comment]
@imsnif I'm wondering if it makes sense to create plugin disk caches beneath the top-level of the zellij plugin directory. This way immediate disk entries could be retrieved and then correct/update after an initial thread renders the last recorded positions.

**Comment by imsnif** [comment]
This should be solved in the recent version
